services:
    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_VERSION=${MYSQL_VERSION:-latest}
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-dev}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE:-default}'
            MYSQL_USER: '${DB_USERNAME:-dev}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-dev}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql:/var/lib/mysql'
            - './mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - dev
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-dev}" ]
            retries: 3
            timeout: 5s
        restart: unless-stopped

    pgsql:
        image: 'postgres:${PGSQL_VERSION:-latest}'
        shm_size: 1g
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-dev}'
            POSTGRES_DB: '${DB_DATABASE:-default}'
            POSTGRES_USER: '${DB_USERNAME:-dev}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-dev}'
        volumes:
            - 'pgsql:/var/lib/postgresql/data'
            - './pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - dev
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s
        restart: unless-stopped

    pgadmin:
        image: 'dpage/pgadmin4:${PGADMIN_VERSION:-latest}'
        environment:
            - 'PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-dev@example.com}'
            - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-dev}'
        ports:
            - '${PGADMIN_PORT:-5050}:80'
        volumes:
            - pgadmin:/var/lib/pgadmin
        networks:
            - dev
        depends_on:
            - pgsql
        restart: unless-stopped

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        networks:
            - dev
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
        restart: unless-stopped

    redis-webui:
        image: 'erikdubbelboer/phpredisadmin:latest'
        environment:
            - 'REDIS_1_HOST=${REDIS_WEBUI_CONNECT_HOST:-redis}'
            - 'REDIS_1_PORT=${REDIS_WEBUI_CONNECT_PORT:-6379}'
        volumes:
            - './redis/includes/config.sample.inc.php:/src/app/includes/config.sample.inc.php'
        ports:
            - '${REDIS_WEBUI_PORT:-9987}:80'
        networks:
            - dev
        depends_on:
            - redis
        restart: unless-stopped

    elasticsearch:
        build:
            context: ./elasticsearch
            args:
                - ELK_VERSION=${ELK_VERSION:-9.0.1}
        volumes:
            - elastic:/usr/share/elasticsearch/data
        environment:
            - 'cluster.name=dev-cluster'
            - 'node.name=dev-node'
            - 'bootstrap.memory_lock=true'
            - 'xpack.security.enabled=false'
            - 'xpack.security.transport.ssl.enabled=false'
            - 'ES_JAVA_OPTS=-Xms2g -Xmx2g'
            - 'cluster.initial_master_nodes=dev-node'
            - 'transport.host=127.0.0.1'
            - 'http.host=0.0.0.0'
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports:
            - '9200:9200'
            - '9300:9300'
        networks:
            - dev
        restart: unless-stopped

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        environment:
            MP_MAX_MESSAGES: 5000
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        networks:
            - dev
        restart: unless-stopped

volumes:
    mysql:
        driver: local
    pgsql:
        driver: local
    pgadmin:
        driver: local
    elastic:
        driver: local

networks:
    dev:
        driver: bridge
